In [ ]:
a=1, b=2, c=3, d=4, e=5, f=6, g=7, h=8, i=9, j=10, k=11, l=12, m=13, n=14, o=15, p=16, q=17, r=18, s=19, t=20, u=21, v=22, w=23, x=24, y=25, z=26

In [11]:
import numpy as np
Matrix_1=np.array([[4,12,1],[1,1,17]])
Matrix_2=np.array([[2,0,2],[2,7,3]])
print('1st Matrix:\n',Matrix_1)
print('2nd Matrix:\n',Matrix_2)

1st Matrix:
 [[ 4 12  1]
 [ 1  1 17]]
2nd Matrix:
 [[2 0 2]
 [2 7 3]]


In [166]:
Matrix_3=Matrix_1+Matrix_2
print('3rd Matrix(Matrix Addition):\n',Matrix_3)

3rd Matrix(Matrix Addition):
 [[ 6 12  3]
 [ 3  8 20]]


In [108]:
Matrix_4=Matrix_1*2
print('4th Matrix(Scalar Multiplication):\n',Matrix_4)

4th Matrix(Scalar Multiplication):
 [[ 8 24  2]
 [ 2  2 34]]


In [112]:
Matrix_5=Matrix_2.T
print('5th Matrix(Matrix Transpose):\n',Matrix_5)

5th Matrix(Matrix Transpose):
 [[2 2]
 [0 7]
 [2 3]]


In [134]:
Matrix_6=np.dot(Matrix_3, Matrix_5)
print('6th Matrix(Matrix Multiplication):\n',Matrix_6)

6th Matrix(Matrix Multiplication):
 [[ 18 105]
 [ 46 122]]


In [154]:
Sum_Matrix_3=np.sum(Matrix_3)
print('Sum of all elements in the 3rd Matrix:',Sum_Matrix_3)

Sum of all elements in the 3rd Matrix: 52


In [156]:
Matrix_7=np.zeros((2, 3), dtype=int)
print('7th Matrix(Zero Matrix):\n', matrix7)

7th Matrix(Zero Matrix):
 [[0 0 0]
 [0 0 0]]


In [12]:
import numpy as np
Matrix_1=np.array([[4,12,1],[1,1,17]])
Matrix_2=np.array([[2,0,2],[2,7,3]])
Matrix_3=Matrix_1+Matrix_2
Matrix_4=Matrix_1*2
Matrix_5=Matrix_2.T
Matrix_6=np.dot(Matrix_3, Matrix_5)
Sum_Matrix_3=np.sum(Matrix_3)
Matrix_7=np.zeros((2, 3), dtype=int)
print('1st Matrix:\n',Matrix_1,
      '\n2nd Matrix:\n',Matrix_2,
      '\n3rd Matrix(Matrix Addition):\n',Matrix_3,
      '\n4th Matrix(Scalar Multiplication):\n',Matrix_4,
      '\n5th Matrix(Matrix Transpose):\n',Matrix_5,
      '\n6th Matrix(Matrix Multiplication):\n',Matrix_6,
      '\nSum of all elements in the 3rd Matrix:',Sum_Matrix_3,
      '\n7th Matrix(Zero Matrix):\n', Matrix_7)

1st Matrix:
 [[ 4 12  1]
 [ 1  1 17]] 
2nd Matrix:
 [[2 0 2]
 [2 7 3]] 
3rd Matrix(Matrix Addition):
 [[ 6 12  3]
 [ 3  8 20]] 
4th Matrix(Scalar Multiplication):
 [[ 8 24  2]
 [ 2  2 34]] 
5th Matrix(Matrix Transpose):
 [[2 2]
 [0 7]
 [2 3]] 
6th Matrix(Matrix Multiplication):
 [[ 18 105]
 [ 46 122]] 
Sum of all elements in the 3rd Matrix: 52 
7th Matrix(Zero Matrix):
 [[0 0 0]
 [0 0 0]]


NameError: name 'ihga' is not defined